### PR TITLE
osrm-backend CI: master/release branch build check and PR build check

### PR DESCRIPTION
**Pull request by wangyoucao577**
# Issue

Closes https://github.com/Telenav/osrm-backend/issues/148

- Check every PR that targets to `master/release` branch; 
- Check every push for `master/release` branch; 
- Build both `Debug` and `Release`; 
- Build on both `ubuntu` and `macosx`; 

PS: Currently only **build** check, we can have more `unittests` later.      

Also updated doc: https://github.com/Telenav/osrm-backend/wiki/Automation-by-GitHub-Actions

### CODE REVIEW

**Comment by CodeBear801** [comment]
Just for discussion:

This `action` is mainly target for `Build` check for `C++ based code`, and later could add more about `unit test`.  We have different CI for `go based code` in https://github.com/Telenav/osrm-backend/issues/209.  

More thinking about this part: Since `monorepo` is popular solution for code base management, our code repo contains different language should also be reasonable, so for different language or different **purpose**, it should be OK create different CI for them, as long as they have correct way to **trigger**, **small** and **quick**

**Comment by wangyoucao577** [comment]
> Just for discussion:
> 
> This `action` is mainly target for `Build` check for `C++ based code`, and later could add more about `unit test`. We have different CI for `go based code` in #209.
> 
> More thinking about this part: Since `monorepo` is popular solution for code base management, our code repo contains different language should also be reasonable, so for different language or different **purpose**, it should be OK create different CI for them, as long as they have correct way to **trigger**, **small** and **quick**

Actually I think the better way is  still to split them into different repos...It's more common on GitHub: create repo for difficult requirement. For instance, it's difficult to find a very huge repo that contains discreted components.

**Comment by CodeBear801** [comment]
> > Just for discussion:
> > This `action` is mainly target for `Build` check for `C++ based code`, and later could add more about `unit test`. We have different CI for `go based code` in #209.
> > More thinking about this part: Since `monorepo` is popular solution for code base management, our code repo contains different language should also be reasonable, so for different language or different **purpose**, it should be OK create different CI for them, as long as they have correct way to **trigger**, **small** and **quick**
> 
> Actually I think the better way is still to split them into different repos...It's more common on GitHub: create repo for difficult requirement. For instance, it's difficult to find a very huge repo that contains discreted components.
> Maybe only Google uses a super huge monorepo?

`monorepo` requires a lot of efforts on build/dependency management/CI.  Agree its not easy without carefully thinking and prepare for huge amount effort on tooling(cloud storage, distribute compilation, version management).  I take back the description for `popular`, I should say, `monorepo` is popular in several giant companies. 

For open source community, I think they works very healthy with `manyrepo`.  :)
For large organization's perspective, `monorepo` helps to guarantee consistency of `dependencies`, they call it `one version` rule, developers must not have a choice when adding a dependency onto some library that is already in use in the organization.

`monorepo` might not suit for company wise for everyone, but could be a good choice for `functionality wise`.  Like we have a single `repo` for `navigation` backend, all related information should be put into the same repository, development code, testing cases, etc.

**Comment by wangyoucao577** [comment]
> > > Just for discussion:
> > > This `action` is mainly target for `Build` check for `C++ based code`, and later could add more about `unit test`. We have different CI for `go based code` in #209.
> > > More thinking about this part: Since `monorepo` is popular solution for code base management, our code repo contains different language should also be reasonable, so for different language or different **purpose**, it should be OK create different CI for them, as long as they have correct way to **trigger**, **small** and **quick**
> > 
> > 
> > Actually I think the better way is still to split them into different repos...It's more common on GitHub: create repo for difficult requirement. For instance, it's difficult to find a very huge repo that contains discreted components.
> > Maybe only Google uses a super huge monorepo?
> 
> `monorepo` requires a lot of efforts on build/dependency management/CI. Agree its not easy without carefully thinking and prepare for huge amount effort on tooling(cloud storage, distribute compilation, version management). I take back the description for `popular`, I should say, `monorepo` is popular in several giant companies.
> 
> For open source community, I think they works very healthy with `manyrepo`. :)
> For large organization's perspective, `monorepo` helps to guarantee consistency of `dependencies`, they call it `one version` rule, developers must not have a choice when adding a dependency onto some library that is already in use in the organization.
> 
> `monorepo` might not suit for company wise for every team, but could be a good choice for `functionality wise monorepo`. Like we have a single `repo` for `navigation backend`, all related information should be put into the same repository, development code/document, testing cases, regression tools, visualization tools, etc.
> The target is, easier CI/CD, and easier to apply same security rule/legal rule to all source code. And most important of all, we could guarantee final pull request is atomic: pull request not contains the change for code, but document update and tests to guarantee target has been reached and no regression.

`monorepo` is very good for team that work together closely, and the automation system need to carefully designed and suited to improve overall efficiency. On the other hand, the open source community is distributed and discreted. `manyrepos` will be better since people only need to care their own `repo` instead of a big system. Also, it's no necessary to have people maintain and design the centerialized automation system.

**Pull request merged**
