### PR TITLE
Enable clang-format check

### LINKED ISSUE #383: Enable cpp code format

### PR DESCRIPTION
**Pull request by wangyoucao577**
# Issue

- Targeting issue: the issue will be CLOSED once the PR merged. If there is no issue that addresses the problem, please open a corresponding issue and link it here. Uses the [Closes keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to close them automatically.     
Closes #383 

- Any other related issue? Mention them here.    

## Description    
A summary description for what the PR achieves.           

- `.h/.cpp` changes only due to format.     
- The PR check will fail if any cpp code doesn't formatted.    

## Tasklist

 - [x] CHANGELOG-FORK.md entry ([CHANGELOG](https://github.com/Telenav/osrm-backend/wiki/CHANGELOG))
 - [ ] [profiles/CHANGELOG.md](https://github.com/Telenav/osrm-backend/blob/master/profiles/CHANGELOG.md) entry if any `Lua` changes   
 - [ ] update relevant [Wiki pages](https://github.com/Project-OSRM/osrm-backend/wiki)
 - [ ] add tests (see [testing documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/testing.md)

## Prerequirements
- Want to contribute? Great! First, please read this page [Contribution Guidelines](https://github.com/Telenav/osrm-backend/wiki/Contribution-Guidelines).    
- If your PR is still work in progress please attach the relevant label.

### CODE REVIEW

**Comment by CodeBear801** [comment]
Enable `clang-format` is great for unifying coding style.  
The change to existing OSRM code will make it hard to be merged for later, do we have way to ignore change to existing code but only to new code?

**Comment by wangyoucao577** [comment]
> Enable `clang-format` is great for unifying coding style.
> The change to existing OSRM code will make it hard to be merged for later, do we have way to ignore change to existing code but only to new code?

Actually only the codes that we changed didn't follow the rules, so all them has been formatted again in this PR. After that, only new codes will be affected.

**Comment by CodeBear801** [comment]
> > Enable `clang-format` is great for unifying coding style.
> > The change to existing OSRM code will make it hard to be merged for later, do we have way to ignore change to existing code but only to new code?
> 
> Actually only the codes that we changed didn't follow the rules, so all them has been formatted again in this PR. After that, only new codes will be affected.

Copy that, this is what I want to confirm.  Thanks.

**Review by CodeBear801 — APPROVED** [review]

**Comment by wangyoucao577** [comment]
The build error on mac OS is caused by Github macOS runner has upgrade to Apple Clang 12. See more in https://github.com/Telenav/osrm-backend/issues/385. 
I'd like to forcely merge this PR, and fix the build error in next one.

**Pull request merged**
