### PR TITLE
add new car profile and libs for unidb

### PR DESCRIPTION
**Pull request by hellotechx**
# Issue

Lua profile supports unidb.
Duplicate car.lua and rename car-unidb.lua.
Duplicate the folder of lib and rename lib-unidb.
Since almost half of files in lib folder need to be changed, instead of duplicate each of them in original folder, duplicate the whole folder.

### CODE REVIEW

**Comment by wangyoucao577** [comment]
@hellotechx  It looks good to me. But please:      
- mention the issue link the PR for in PR description(link it in "linked issue" in right panel will result to close the issue automatically once the PR merged) 
- mark milestone this PR for 

One more question, could you please also write basic maintain/modify rules in the profiles/README.md instead of commit a empty one? Next time then always append changes when have anything change related `Lua`, right?

**Comment by hellotechx** [comment]
@wangyoucao577 
Linked. 
README.md will be updated with traffic signal since I haven't figure out the content/format for this PR.
There are two coming PRs.
One is revert PR#67
One is traffic signal + README.md updated

**Comment by hellotechx** [comment]
Remove the empty README for this PR. 
Will add it back in coming PR.

**Comment by wangyoucao577** [comment]
Then the `car-unidb.lua` will only invoke functions from `lib-unidb/`, and `car.lua` will only invoke functions from `lib/`, right?

**Comment by hellotechx** [comment]
> Then the `car-unidb.lua` will only invoke functions from `lib-unidb/`, and `car.lua` will only invoke functions from `lib/`, right?

Yes. Eventually any pattern of xxx-unidb.lua should only invoke lib-unidb/*
Any pattern of xxx.lua should only invoke lib/*

**Comment by wangyoucao577** [comment]
> > Then the `car-unidb.lua` will only invoke functions from `lib-unidb/`, and `car.lua` will only invoke functions from `lib/`, right?
> 
> Yes. Eventually any pattern of xxx-unidb.lua should only invoke lib-unidb/*
> Any pattern of xxx.lua should only invoke lib/*

This could be the most important rule in the next `README.md`. It looks good to me. 
@CodeBear801  Please help to review and approve it if you're ok with it a.s.a.p. @hellotechx  is ready to improve `.lua` for `traffic_signals` and `stop_sign`.

**Comment by CodeBear801** [comment]
Great.  @hellotechx, please add a file `changelog.md` to record our changes compare with original script.

It will contain information like:

```
- change xxx value from yyy to zzz for mmm purpose
- add new attribute of hhh for eee purpose
...
```

**Pull request merged**
