### PR TITLE
Feature/ranking

### PR DESCRIPTION
**Pull request by wangyoucao577**
# Issue

What issue is this PR targeting? If there is no issue that addresses the problem, please open a corresponding issue and link it here.

Please read our [documentation](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/releasing.md) on release and version management.
If your PR is still work in progress please attach the relevant label.

https://github.com/Telenav/osrm-backend/issues/86

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?
https://github.com/Telenav/osrm-backend/issues/86

### CODE REVIEW

**Comment by CodeBear801** [comment]
The implementation of ranking is great, just several common questions want to discuss with you:
1. Is blocking flow must be avoided?  For this [route](https://www.google.com/maps/dir/37.052579,-121.2533067/Los+Angeles,+California/@36.9565378,-121.1443945,9.91z/data=!4m9!4m8!1m0!1m5!1m1!1s0x80c2c75ddc27da13:0xe22fdf6f254608f4!2m2!1d-118.2436849!2d34.0522342!3e0), even there is blocking flow, I5 might be the only choice.  Please help to confirm what's the influence of `blocking flow`?

2. Its a clear abstraction to have rankingstrategy.  Just confirm, you expect there could be different version of ranking strategy.  So `Rank()` could be an interface for people to implement. 

3. The define of osrmv1 means all compatible changes will go to osrmv1, if there is none-compatible change, we will define osrmv2.
    Then what's the influence of existing functions like here?  Do we expect them re-implement it or adjust code.  Would it make sense to use osrmv1 to make logic to be competitive?

**Comment by wangyoucao577** [comment]
> The implementation of ranking is great, just several common questions want to discuss with you:
> 
> 1. Is blocking flow must be avoided?  For this [route](https://www.google.com/maps/dir/37.052579,-121.2533067/Los+Angeles,+California/@36.9565378,-121.1443945,9.91z/data=!4m9!4m8!1m0!1m5!1m1!1s0x80c2c75ddc27da13:0xe22fdf6f254608f4!2m2!1d-118.2436849!2d34.0522342!3e0), even there is blocking flow, I5 might be the only choice.  Please help to confirm what's the influence of `blocking flow`?
> 2. Its a clear abstraction to have rankingstrategy.  Just confirm, you expect there could be different version of ranking strategy.  So `Rank()` could be an interface for people to implement.
> 3. The define of osrmv1 means all compatible changes will go to osrmv1, if there is none-compatible change, we will define osrmv2.
>    Then what's the influence of existing functions like here?  Do we expect them re-implement it or adjust code.  Would it make sense to use osrmv1 to make logic to be competitive?

1. Good question! The short answer is I'm not sure. For the route sample you provided, I think it's ok to avoid it because we possible go through with US101 or 99. But we do get route fail due to live traffic when we test against the blocking-only traffic applied OSRM. I implemented avoid blocking flow/incident as default behavior since they're current understanding. We can change the behavior when we met real issue by this. 

2. Yes, maybe `rankbydistance` or some thing mixed. The `Rank()` should be refactored as interface once we can have another package to implement it. 

3. Currently OSRM's all services have same version `v1`, so I use `osrmv1` to collect all OSRM API related definition and implementation together. A better idea maybe `routev1/matchv1/tablev1/...` but a little more complex. When we have `osrmv2` or maybe `routev2` due to some incompatible changes, callers have to do some change, e.g. forward compatible or `v2` only, it depends on callers. How's your idea?

**Comment by CodeBear801** [comment]
> > The implementation of ranking is great, just several common questions want to discuss with you:
> > 
> > 1. Is blocking flow must be avoided?  For this [route](https://www.google.com/maps/dir/37.052579,-121.2533067/Los+Angeles,+California/@36.9565378,-121.1443945,9.91z/data=!4m9!4m8!1m0!1m5!1m1!1s0x80c2c75ddc27da13:0xe22fdf6f254608f4!2m2!1d-118.2436849!2d34.0522342!3e0), even there is blocking flow, I5 might be the only choice.  Please help to confirm what's the influence of `blocking flow`?
> > 2. Its a clear abstraction to have rankingstrategy.  Just confirm, you expect there could be different version of ranking strategy.  So `Rank()` could be an interface for people to implement.
> > 3. The define of osrmv1 means all compatible changes will go to osrmv1, if there is none-compatible change, we will define osrmv2.
> >    Then what's the influence of existing functions like here?  Do we expect them re-implement it or adjust code.  Would it make sense to use osrmv1 to make logic to be competitive?
> 
> 1. Good question! The short answer is I'm not sure. For the route sample you provided, I think it's ok to avoid it because we possible go through with US101 or 99. But we do get route fail due to live traffic when we test against the blocking-only traffic applied OSRM. I implemented avoid blocking flow/incident as default behavior since they're current understanding. We can change the behavior when we met real issue by this.
> 2. Yes, maybe `rankbydistance` or some thing mixed. The `Rank()` should be refactored as interface once we can have another package to implement it.
> 3. Currently OSRM's all services have same version `v1`, so I use `osrmv1` to collect all OSRM API related definition and implementation together. A better idea maybe `routev1/matchv1/tablev1/...` but a little more complex. When we have `osrmv2` or maybe `routev2` due to some incompatible changes, callers have to do some change, e.g. forward compatible or `v2` only, it depends on callers. How's your idea?

For #3, I just feel those version should not be part of the code but a package name or namespace in C++.
osrm define the protocol between OSRM and golang, its the contract between them.  My thinking is, in golang, we should have test to guarantee the API is the same as we expected, when anything changes we will know.  All other golang code will only follow one protocol.

**Comment by wangyoucao577** [comment]
> > > The implementation of ranking is great, just several common questions want to discuss with you:
> > > 
> > > 1. Is blocking flow must be avoided?  For this [route](https://www.google.com/maps/dir/37.052579,-121.2533067/Los+Angeles,+California/@36.9565378,-121.1443945,9.91z/data=!4m9!4m8!1m0!1m5!1m1!1s0x80c2c75ddc27da13:0xe22fdf6f254608f4!2m2!1d-118.2436849!2d34.0522342!3e0), even there is blocking flow, I5 might be the only choice.  Please help to confirm what's the influence of `blocking flow`?
> > > 2. Its a clear abstraction to have rankingstrategy.  Just confirm, you expect there could be different version of ranking strategy.  So `Rank()` could be an interface for people to implement.
> > > 3. The define of osrmv1 means all compatible changes will go to osrmv1, if there is none-compatible change, we will define osrmv2.
> > >    Then what's the influence of existing functions like here?  Do we expect them re-implement it or adjust code.  Would it make sense to use osrmv1 to make logic to be competitive?
> > 
> > 
> > 
> > 1. Good question! The short answer is I'm not sure. For the route sample you provided, I think it's ok to avoid it because we possible go through with US101 or 99. But we do get route fail due to live traffic when we test against the blocking-only traffic applied OSRM. I implemented avoid blocking flow/incident as default behavior since they're current understanding. We can change the behavior when we met real issue by this.
> > 2. Yes, maybe `rankbydistance` or some thing mixed. The `Rank()` should be refactored as interface once we can have another package to implement it.
> > 3. Currently OSRM's all services have same version `v1`, so I use `osrmv1` to collect all OSRM API related definition and implementation together. A better idea maybe `routev1/matchv1/tablev1/...` but a little more complex. When we have `osrmv2` or maybe `routev2` due to some incompatible changes, callers have to do some change, e.g. forward compatible or `v2` only, it depends on callers. How's your idea?
> 
> For `#3`, I just feel those version should not be part of the code but a package name or namespace in C++.
> osrm define the protocol between OSRM and golang, its the contract between them. My thinking is, in golang, we should have test to guarantee the API is the same as we expected, when anything changes we will know. All other golang code will only follow one protocol.

For 3, good point. Callers could import different package version for different version APIs. So in this API implementation, I agree to remove the `v1`. Also, I think split them to `osrm/route, osrm/table, ...` will be better. I'll do the change soon.

**Pull request merged**
